### ISSUE TITLE
Copy to clipboard fails

### ISSUE THREAD

**Issue by der** [epimorphics/registry-api-active-docs#35]
On ubuntu 16.04/Chrome the "copy to clipboard" action on the URL silently fails. No console message or visible response, nothing on the clipboard.

**Comment by ijdickinson** [comment]
Do you have Flashblock or Ghostery or some other Flash-preventing plugin installed? Copy-to-clipboard is not permitted in JavaScript, so it requires Flash to work. Does copy-to-clipboard work for you on Github, because I'm using exactly the same utility that they do

**Comment by der** [comment]
No aware of having any flash-preventing plugin. Copy to clipboard works for me on github and codebasehq

**Comment by ijdickinson** [comment]
It's working for me still, and I'm not convinced that there's going to be a big difference between Ubuntu 16.04 and 17.04. 

At your convenience, can you look on the network tab in dev tools when you click on the clipboard for the first time please? It should show a network request to ZeroClipboard.swf, and that should return 200 OK.

Also, which version of nodejs are you running when you launch `npm run dev`?

**Comment by der** [comment]
Checking more closely, it runs for me under `npm run dev`

The failure happens when running the `dist` package under tomcat/apache (simulating the intended deployment). Under that set up there is no network request to `ZeroClipboard.swf` at all.

**Comment by ijdickinson** [comment]
I'm not sure how best to diagnose this. If I take the deployment archive, and serve it out from my local Apache by linking `dist` to `~/public_html`, the copy-to-clipboard feature works fine.

Can you create a step-by-step guide to recreating your setup so that I can investigate it?

**Comment by der** [comment]
Addition of `moviePath` has fixed it! Presumably differing versions of OS Flash support.
