### ISSUE TITLE
Payload text area not resizeable

### ISSUE THREAD

**Issue by der** [epimorphics/registry-api-active-docs#37]
The text areas for payload is small and not resizeable on Chrome.

If it's hard to allow resizing (due to codemirror?) then could we increase the payload box height?

**Comment by ijdickinson** [comment]
I'll see about making it resizable. I'm leery of making it too high as we tend to use larger screens than many people, giving a misleading impression of what's visible above-the-fold.

**Comment by ijdickinson** [comment]
As you surmised, the normal style of resizable window is hard to do with CodeMirror. I've added a patch with a possible solution (automatic resizing). I'm not 100% convinced this is the right answer, but see what you think.

**Comment by der** [comment]
Seems good. May not be the "right" answer but definitely good enough for now. Thanks.
