### ISSUE TITLE
Deep linking path parameters?

### ISSUE THREAD

**Issue by der** [epimorphics/registry-api-active-docs#39]
Is it possible to set a path parameter through deep linking?

E.g. so could link to the "list named register" operation passing in the name of the register to list?

Experimentation suggests not but I might be misunderstanding.

**Comment by ijdickinson** [comment]
Do you mean you want to set a segment variable by deep linking? If so, not yet, but I can add that.

**Comment by der** [comment]
Yes, that's what I meant. Jax-rs and others use the term "path parameter" which is why I called it that. Segment parameter implies it can only be a full path segment which maybe is more accurate in this case. If it is not too hard to add then might dig us out of the hole of how to represent status update actions.

**Comment by ijdickinson** [comment]
Hmm, I don't use JAX-RS, so I have no idea what that community prefers, but I've just checked and RAML actually uses "URI parameter" within a URI template "as defined by level 2 of RFC6570". 

We should use a consistent terminology. URI parameter seems like it should be acceptably close to JAX-RS.

**Comment by ijdickinson** [comment]
My proposal here is to allow expressions of the form `urlParameter=value` in the URL as a query parameter, to pre-instantiate URL template parameters. That would mean that there was no namespacing between URL parameter terms and API query parameter names, so they could in theory clash. Is that likely to be a problem, do you think?

**Comment by der** [comment]
No, I think that's fine.

**Comment by ijdickinson** [comment]
@der Please confirm

**Comment by der** [comment]
Brilliant, thanks.
