### ISSUE TITLE
Parsing of prefixed path parameters fails

### ISSUE THREAD

**Issue by der** [epimorphics/registry-api-active-docs#40]
I tried to create an API entry to set the status of a register.

This is a POST to the item version of the URL so I tried a path of: `/_:{register}:`

However this creates a URI segment variable `_register` but leaves the template as `test/_:{register}` and setting the segment variable then doesn't work.

**Comment by ijdickinson** [comment]
Sounds like an issue with the RAML parser, and not the first one that I've had. Bother.

**Comment by ijdickinson** [comment]
A simple workaround for this issue would be to assume that no URL parameter legitimately has a leading underscore in the name. Therefore any that do can be assumed to be the product of a parsing error, and repaired. Would that be acceptable?

**Comment by der** [comment]
Sure, if that's the easiest thing to do

**Comment by ijdickinson** [comment]
Certainly easier than diagnosing and fixing the RAML grammar

**Comment by ijdickinson** [comment]
@der Please confirm

**Comment by der** [comment]
Confirmed, thanks
