### ISSUE TITLE
Deep linked dates don't show in picker

### ISSUE THREAD

**Issue by der** [epimorphics/registry-api-active-docs#41]
The example deep link:

    url=%2F%7Bregister%7D&method=get&_format=csv&register=measurement-types&min-std%3AdateFrom=2017-06-03

works in that the correct target URL is generated and runs and the `min-std:dateFrom` parameter is ticked, but the data picker does not show the date set.

This is not a priority. If it's other than trivial then leave it. I can drop these examples or just accept the current behaviour.

**Comment by ijdickinson** [comment]
Bother, my recent changes have caused a regression here: now the generated URL has the date in the wrong format. Investigating.

**Comment by ijdickinson** [comment]
@der Pre-selecting dates should now work as expected

**Comment by der** [comment]
Brilliant, thanks. Deployed and working.
